name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: npm-package-dist
          path: dist/package

      - uses: actions/upload-artifact@v4
        with:
          name: browser-extension-chrome
          path: dist/extension/chrome

      - uses: actions/upload-artifact@v4
        with:
          name: browser-extension-firefox
          path: dist/extension/firefox
